name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flet requests

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'

      - name: Setup Android SDK Licenses
        run: |
          mkdir -p ${ANDROID_HOME}/licenses
          echo -e "\n2c4dfa0b36645dd23a31317b3540114e047c00a6" > ${ANDROID_HOME}/licenses/android-sdk-license
          echo -e "\n84831b9409646a547e31e3ef48c17a43d2fc21a7" > ${ANDROID_HOME}/licenses/android-sdk-preview-license

      - name: Build APK via Flet
        run: |
          cd $GITHUB_WORKSPACE
          yes | flet build apk .
